<?php

    return[
        [
            'title'=>'Evasion Mansion',
            'description'=>'Alla proprietà si accede da un lungo viale alberati di  Platani e, più all’interno, da qualche albero da frutto. La casa è ben immersa nel verde e lo spiazzo di ghiaia che si apre alla sua destra puo’ essere comodamente utilizzato come parcheggio per le automobili senza dar fastidio alla vivibilita’ dello spazio esterno.',
            'rooms'=> 5,
            'beds'=> 3,
            'bathrooms'=> 2,
            'mq'=> 200,
            'address'=>'Via Daniele Manin, 20121 Milano MI, Italia',
            'latitude' => 45.474233709779696,
            'longitude'=> 9.196667554085849,
            'image'=> null,
            'house_type'=>'Luxe',
            'room_type'=>'proprietà intera',
            'price' => 900,
            'is_visible' => 1,
        ],
        [
            'title'=>'Webguard House',
            'description'=>'Sul lato esterno della casa che affaccia sulla piscina troviamo la doccia esterna e poco più avanti un lavabo in pietra utile per il bucato e l’acqua corrente. Dall\'interno percorrendo le scale possiamo arrivare alla splendida terrazza sul tetto.',
            'rooms'=> 4,
            'beds'=> 3,
            'bathrooms'=> 2,
            'mq'=> 150,
            'address'=>'Via privata Fratelli Gabba, 20121 Milano MI, Italia',
            'latitude' => 45.470526774480874,
            'longitude'=> 9.19041067157059,
            'image'=> null,
            'house_type'=>'Design',
            'room_type'=>'proprietà intera',
            'price' => 700,
            'is_visible' => 1,
        ],
        [
            'title'=>'Moppeatt Mansion',
            'description'=>'In un elegante appartamento in chiave moderna, con parti comuni perfettamente curate. La proprietà, ha un grande ingresso,  dove possiamo trovare due amplissime camere matrimoniali, un soggiorno doppio, cucina abitabile, due bagni, terza camera singola ma comoda, ripostiglio. Gli affacci, molto gradevoli. la doppia esposizione Est-Ovest dona all’appartamento una gradevole luminosità.',
            'rooms'=> 4,
            'beds'=> 3,
            'bathrooms'=> 2,
            'mq'=> 180,
            'address'=>'Piazza Filippo Meda, 20121 Milano MI, Italia',
            'latitude' => 45.46718809804622,
            'longitude'=> 9.19300296180819,
            'image'=> null,
            'house_type'=>'Design',
            'room_type'=>'proprietà intera',
            'price' => 600,
            'is_visible' => 1,
        ],
        [
            'title'=>'B&B Ostuns',
            'description'=>'Il B&B Ostuns è un casale immerso nella quiete. Dispone di tre camere lussuose con bagno privato, balcone e possibilità di colazione in camera. Parcheggio privato ottima location per raggiungere il centro dove potrete trovare luoghi unici di interesse storico culturale e dove la cucina fanno da padrone. Siamo pronti ad ospitarvi in un luogo ricco di arte e tradizione , benvenuti al B&B Ostuns',
            'rooms'=> 1,
            'beds'=> 1,
            'bathrooms'=> 1,
            'mq'=> 250,
            'address'=>'  Piazza Armando Diaz, 3, 20121 Milano MI, Italia',
            'latitude' => 45.46227628658326,
            'longitude'=> 9.190435283899149,
            'image'=> null,
            'house_type'=>'B&B',
            'room_type'=>'Stanza doppia',
            'price' => 120,
            'is_visible' => 1,
        ],
        [
            'title'=>'B&B Coppercolt',
            'description'=>'In un tranquillo vicolo dell\'antica Milano a cinque minuti dal Duomo una stanza dotata di tutti i comfort, riscaldamento, aria condizionata, televisore lcd, frigorifero e ogni mattina ricca prima colazione continentale.',
            'rooms'=> 5,
            'beds'=> 8,
            'bathrooms'=> 5,
            'mq'=> 230,
            'address'=>'Piazza Borromeo, 25019 Sirmione BS, Italia',
            'latitude' => 45.46374191630525,
            'longitude'=> 9.182466831144183,
            'image'=> null,
            'house_type'=>'B&B',
            'room_type'=>'Stanza doppia',
            'price' => 135,
            'is_visible' => 1,
        ],
        [
            'title'=>'Richbard Mansion',
            'description'=>'Vivere nell’abbraccio della natura a due passi dal centro.
            In un’area in passato destinata a vivaio, all’interno di una cornice completamente riqualificata di un Parco milanese, viene edificato la Richbard Mansion, una moderna residenza che unisce il tessuto della città al verde urbano più puro.
            Una posizione ideale per chi vuole vivere nel verde e in tranquillità senza rinunciare a tutte le comodità della città.',
            'rooms'=> 5,
            'beds'=> 4,
            'bathrooms'=> 2,
            'mq'=> 170,
            'address'=>' Via della Guastalla, 20121 Milano MI, Italia',
            'latitude' => 45.460267966423714,
            'longitude'=> 9.197809493101602,
            'image'=> null,
            'house_type'=>'Luxe',
            'room_type'=>'proprietà intera',
            'price' => 1000,
            'is_visible' => 1,
        ],
        [
            'title'=>'Livingbeard House',
            'description'=>'Livingbeard House  sviluppate su due differenti livelli con ampi giardini di proprietà. In posizione tranquilla e soleggiata, nel verde e a due passi dalla riva del lago. Le caratteristiche che contraddistinguono le ville sono determinate da un alto comfort abitativo a livello termico e acustico, gestione domotica, grandi vetrate del soggiorno affacciate proprio sul grande giardino esterno. Il box è dotato di  ricarica per veicoli elettrici, la fibra ottica, le finiture supermoderne a tua scelta. L\'accesso al lago ed alle sue bellissime passeggiate, ai ristoranti stellati, ai negozi, al porto pubblico dal quale partono i traghetti, al porto privato per la propria imbarcazione, alla spiaggia.',
            'rooms'=> 3,
            'beds'=> 2,
            'bathrooms'=> 2,
            'mq'=> 90,
            'address'=>'Via Venticinque Aprile, 25019 Sirmione BS, Italia',
            'latitude' => 45.48153802170032,
            'longitude'=> 10.608493480603698,
            'image'=> null,
            'house_type'=>'Wow',
            'room_type'=>'proprietà intera',
            'price' => 550,
            'is_visible' => 1,
        ],
        [
            'title'=>'B&B Addook ',
            'description'=>' Il B&B Addook Daniele è una caratteristica dominante della natura selvaggia e delle splendide rive del Lago di Garda, in posizione privilegiata circondata da paesaggi mozzafiato. la casa Addook fu costruito verso la fine del XIX secolo da una famiglia aristocratica. Puoi ancora vedere e sentire questo patrimonio nell\'architettura originale restaurata e conservata e nei mobili antichi accuratamente selezionati.',
            'rooms'=> 9,
            'beds'=> 12,
            'bathrooms'=> 8,
            'mq'=> 250,
            'address'=>'Via Pietro Amendola, 25019 Sirmione BS, Italia',
            'latitude' => 45.47238105003527,
            'longitude'=> 10.60038539793561,
            'image'=> null,
            'house_type'=>'B&B',
            'room_type'=>'Stanza doppia',
            'price' => 550,
            'is_visible' => 1,
        ],
        [
            'title'=>'B&B Gentleland ',
            'description'=>'Il B&B Gentleland è immerso nella natura.
            Il DESIGN del B&B vi offre un tocco di originalità nella Piscina a Sfioro, tuffatevi qui e vi sembrerà di abbracciare il paesaggio intero, una bella sensazione di relax. Gli interni sono raffinati e curati, qui sarete ben accolti.',
            'rooms'=> 7,
            'beds'=> 7,
            'bathrooms'=> 5,
            'mq'=> 210,
            'address'=>'Via Marolda, 9, 25019 Sirmione BS, Italia',
            'latitude' => 45.4724113909829,
            'longitude'=> 10.610593282199176,
            'image'=> null,
            'house_type'=>'B&B',
            'room_type'=>'Stanza singola',
            'price' => 350,
            'is_visible' => 1,
        ],
        [
            'title'=>'Glulmea house ',
            'description'=>'Il Casale si affacciato sui nostri vigneti. Circondato da un giardino di 1000 mq interamente recintato, con prato all\'inglese, piscina ad acqua salata, ulivi, alberi da frutto e rose antiche.
            La Cantina di vinificazione è a soli 500 metri, per cui, se vorrete, respirerete l\’atmosfera di un luogo dove si fa vino, tra degustazioni, visite in Cantina e passeggiate tra le vigne.',
            'rooms'=> 4,
            'beds'=> 3,
            'bathrooms'=> 2,
            'mq'=> 120,
            'address'=>'Via Lecco, 25019 Sirmione BS, Italia',
            'latitude' => 45.472260981004894,
            'longitude'=> 10.602423270558205,
            'image'=> null,
            'house_type'=>'campagna',
            'room_type'=>'proprietà intera',
            'price' => 400,
            'is_visible' => 1,
        ],
        [
            'title'=>'Merryless ',
            'description'=>'In tranquilla zona residenziale troviamo Merryless con giardino e un\'ampia piscina. lo stabile è strutturato : Ingresso, ampio soggiorno, cucina abitabile, tre camere, due servizi, ampio piano interrato e garage doppio. Climatizzata, riscaldamento a pavimento con pompa di calore, pannelli solari con 6 kw e batterie di accumulo. serramenti in legno con vetrocamera, impianto di allarme perimetrale-volumetrico.',
            'rooms'=> 5,
            'beds'=> 3,
            'bathrooms'=> 2,
            'mq'=> 160,
            'address'=>'Via dei Fabbri Navali, 36, 00122 Roma RM, Italia',
            'latitude' => 41.728561,
            'longitude'=> 12.2815352,
            'image'=> null,
            'house_type'=>'Design',
            'room_type'=>'proprietà intera',
            'price' => 900,
            'is_visible' => 1,
        ],
        [
            'title'=>'Bellsmith House',
            'description'=>'la Bellsmith House è una piccola casa a pochi passi dal mare. Qui puoi venire a riflettere e lasciarti alle spalle la vita di tutti i giorni. Il paesaggio è tranquillo, con splendide vista sul mare. Ci sono prati colorati, alberi secolari. È un buon posto per un ritiro con se stessi.',
            'rooms'=> 2,
            'beds'=> 2,
            'bathrooms'=> 1,
            'mq'=> 60,
            'address'=>'Piazza Cesario Console, 6, 00122 Roma RM, Italia',
            'latitude' => 41.728561,
            'longitude'=> 12.2815352,
            'image'=> null,
            'house_type'=>'ville',
            'room_type'=>'proprietà intera',
            'price' => 100,
            'is_visible' => 1,
        ],
        [
            'title'=>'Chapgard Mansion',
            'description'=>'La Villa saprà regalarvi rilassanti momenti immersi in quest\'oasi di quiete ed eleganza.',
            'rooms'=> 4,
            'beds'=> 4,
            'bathrooms'=> 2,
            'mq'=>160,
            'address'=>'Via Rutilio Namaziano, 00122 Roma RM, Italia',
            'latitude' => 41.73059620458878,
            'longitude'=> 12.275204582105744,
            'image'=> null,
            'house_type'=>'ville',
            'room_type'=>'proprietà intera',
            'price' => 150,
            'is_visible' => 1,
        ],
        [
            'title'=>'Collmore',
            'description'=>'In questo quartiere, avrete a disposizioni una piccola casa con due camere da letto con balcone/terrazza affacciata su un tranquillissimo giardino privato.
            Questo è un ottimo posto per poter lavora in pace e per divertirsi in qunato a pochi passi dalla casa c\'è la possibilità di usufruire della spiaggia libera.',
            'rooms'=>3,
            'beds'=> 2,
            'bathrooms'=> 2,
            'mq'=>100,
            'address'=>'Via dei Sandolini, 00122 Roma RM, Italia',
            'latitude' => 41.71837293256303,
            'longitude'=> 12.309685764635248,
            'image'=> null,
            'house_type'=>'Co-working',
            'room_type'=>'proprietà intera',
            'price' => 130,
            'is_visible' => 1,
        ],
        [
            'title'=>'Blertam Home',
            'description'=>'Blertam Home ti offre l\'esperienza Airbnb più rilassante e piacevole a soli 5 minuti a piedi dalla stazione centrale di Roma. Ogni camera è completamente rinnovata e ha un bel tocco bohémien. I nostri ospiti potranno godere di design, comfort e la posizione strategica.',
            'rooms'=>3,
            'beds'=> 2,
            'bathrooms'=> 2,
            'mq'=>100,
            'address'=>" Via dell'Appagliatore, 00122 Roma RM, Italia",
            'latitude' => 41.739947717490566,
            'longitude'=> 12.263498076990771,
            'image'=> null,
            'house_type'=>'Co-leaving',
            'room_type'=>'Stanza singola',
            'price' => 80,
            'is_visible' => 1,
        ],
        [
            'title'=>'Collmore Home',
            'description'=>'Country Lodge Vuković si trova a 12 km dall\'ingresso principale del Parco Nazionale. Nelle immediate vicinanze potrete visitare il centro storico e le Barać grotte che sono a soli 7 km da noi.',
            'rooms'=>3,
            'beds'=> 2,
            'bathrooms'=> 2,
            'mq'=>80,
            'address'=>" Via Monte Ortigara, 23032 Bormio SO, Italia",
            'latitude' => 46.47529960794054,
            'longitude'=> 10.370639789481032,
            'image'=> null,
            'house_type'=>'Co-leaving',
            'room_type'=>'proprietà intera',
            'price' => 100,
            'is_visible' => 1,
        ],
        [
            'title'=>'Chalet nel Bosco',
            'description'=>'Relax e Natura in questo Chalet di legno circondato da un immenso bosco, a due passi da Castell’Arquato, nella stupenda cornice di monti innevati.
            Meta ideale per chi vuole fuggire dalla frenesia della città, la casa si trova a un paio d\'ore di macchina da Milano.
            Lo Chalet nel Bosco è perfetto per una fuga romantica in coppia o per un soggiorno in famiglia, per godere dei benefici che la natura offre, in una location unica e suggestiva.',
            'rooms'=>3,
            'beds'=> 2,
            'bathrooms'=> 1,
            'mq'=>75,
            'address'=>"Via Monte Solena, 23032 Bormio SO, Italia",
            'latitude' => 46.47531114730745,
            'longitude'=> 10.374328709385082,
            'image'=> null,
            'house_type'=>'Baite',
            'room_type'=>'proprietà intera',
            'price' => 90,
            'is_visible' => 1,
        ],
        [
            'title'=>'Blertam B&B',
            'description'=>'Il nostro B&B è il posto ideale per vacanze di pace e relax ma anche un ottimo punto di partenza per escursioni d\'interesse storico, paesaggistico e enogastronomico.
            Con spazi completamente dedicati, è adatto a coppie, famiglie o gruppi di amici.',
            'rooms'=>6,
            'beds'=> 8,
            'bathrooms'=> 6,
            'mq'=>230,
            'address'=>"Via Monte Braulio, 23032 Bormio SO, Italia",
            'latitude' => 46.47129472809479,
            'longitude'=> 10.371032227203898,
            'image'=> null,
            'house_type'=>'B&B',
            'room_type'=>'Stanza singola',
            'price' => 95,
            'is_visible' => 1,
        ],
        [
            'title'=>'Cunninggard',
            'description'=>'Cottage autentico e accogliente nel cuore di bormio con una splendida vista. Qui si vive comodamente con la famiglia o gli amici a pochi passi da tutto.',
            'rooms'=>3,
            'beds'=> 2,
            'bathrooms'=> 2,
            'mq'=>105,
            'address'=>"Via Ulrico Martinelli, 23032 Bormio SO, Italia",
            'latitude' => 46.47185424329382 ,
            'longitude'=> 10.367664084129814,
            'image'=> null,
            'house_type'=>'Co-working',
            'room_type'=>'Proprietà intera',
            'price' => 113,
            'is_visible' => 1,
        ],
        [
            'title'=>'Rottbard B&B',
            'description'=>'Il cottage è  all\'avanguardia arredato con tutto il necessario. Il cottage è situato da solo senza alcuna comprensione da parte dei vicini ed è un ottimo punto di partenza se si vuole solo godersi il silenzio, andare a fare una passeggiata su uno dei tanti sentieri escursionistici.',
            'rooms'=>3,
            'beds'=> 2,
            'bathrooms'=> 2,
            'mq'=>115,
            'address'=>"Via Don Angelo Moltrasio, 23032 Bormio SO, Italia",
            'latitude' => 46.469995498605726 ,
            'longitude'=> 10.370540058123652,
            'image'=> null,
            'house_type'=>'Baite',
            'room_type'=>'Proprietà intera',
            'price' => 120,
            'is_visible' => 1,
        ],
        [
            'title'=>'Flaista',
            'description'=>'Vi invitiamo a venire a soggiornare nel nostro piccola casa immerso nel verde. Si trova a pochi passi di un antico borgo, pieno di gente del posto amichevole. Dotato di giardino privato e sistemazioni di lusso, questo è il luogo perfetto per rilassarsi ed esplorare questa bellissima parte d\'Italia.',
            'rooms'=>1,
            'beds'=> 1,
            'bathrooms'=> 1,
            'mq'=>45,
            'address'=>"Via delle Macchiole, 67100 L'Aquila AQ, Italia",
            'latitude' => 42.34639405990262 ,
            'longitude'=> 13.420851459284023,
            'image'=> null,
            'house_type'=>'minicase',
            'room_type'=>'Proprietà intera',
            'price' => 65,
            'is_visible' => 1,
        ],
        [
            'title'=>'Floondewl',
            'description'=>'Innamorati dello splendido paesaggio che circonda questo alloggio meravigliò ;scialet circondato da giardino curatissimo che potrai godertelo in esclusiva respirando aria pura e godersi il panorama tutto verde straiati sull’erba riposarti e prendere il sole a due passi dal laghetto .',
            'rooms'=>1,
            'beds'=> 1,
            'bathrooms'=> 1,
            'mq'=>40,
            'address'=>"Via del Mulino, 67100 L'Aquila AQ, Italia",
            'latitude' => 42.349390337406305 ,
            'longitude'=> 13.382705734990907,
            'image'=> null,
            'house_type'=>'minicase',
            'room_type'=>'Proprietà intera',
            'price' => 73,
            'is_visible' => 1,
        ],
        [
            'title'=>'Phailsta mini-House',
            'description'=>'Questo alloggio unico è l\'ideale per una fuga romantica.
            Immersi nei vigneti dell\'azienda, in una moderna mini casa completa di ogni tipo di confort nel minimo degli spazzi.',
            'rooms'=>1,
            'beds'=> 1,
            'bathrooms'=> 1,
            'mq'=>38,
            'address'=>"Via dei Vestini, 67100 L'Aquila AQ, Italia",
            'latitude' => 42.349390337406305 ,
            'longitude'=> 13.382705734990907,
            'image'=> null,
            'house_type'=>'minicase',
            'room_type'=>'Proprietà intera',
            'price' => 96,
            'is_visible' => 1,
        ],
        [
            'title'=>'Ramney mini-House',
            'description'=>'Loft inserito in un piccolo contesto urbano.
            Dotato di comodo letto matrimoniale e divano letto a due posti. Bagno attrezzato con doccia. Angolo scrittoio con macchina caffè e frigobar.
            Completo di tutti i confort tra cui wi-fi, smart tv con Netflix, aria condizionata e riscaldamento.',
            'rooms'=>1,
            'beds'=> 1,
            'bathrooms'=> 1,
            'mq'=>29,
            'address'=>"Via Barete, 67100 L'Aquila AQ, Italia",
            'latitude' => 42.35285740345461 ,
            'longitude'=> 13.394238712243862,
            'image'=> null,
            'house_type'=>'minicase',
            'room_type'=>'Proprietà intera',
            'price' => 55,
            'is_visible' => 1,
        ],
        [
            'title'=>'Eavsurn',
            'description'=>'È qui! È bello, piccolo e semplice. Se cercate un posto speciale per dormire, ce l\'abbiamo. Abbiamo costruito la nostra piccola casa delle streghe in una zona tranquilla della nostra proprietà ti offrono uno spazio alternativo unico. ',
            'rooms'=>1,
            'beds'=> 1,
            'bathrooms'=> 1,
            'mq'=>37,
            'address'=>" Viale delle Medaglie d'Oro, 67100 L'Aquila AQ, Italia",
            'latitude' => 42.35350852128573 ,
            'longitude'=> 13.402629205681905,
            'image'=> null,
            'house_type'=>'minicase',
            'room_type'=>'Proprietà intera',
            'price' => 75,
            'is_visible' => 1,
        ],
        [
            'title'=>'Mootlen',
            'description'=>'Goditi il tuo soggiorno tranquillo in una casa in legno e in una natura straordinaria. Situato nel parco a soli 20 minuti dal lago. Essere sempre al sole. Con la vostra terrazza privata.',
            'rooms'=>1,
            'beds'=> 1,
            'bathrooms'=> 1,
            'mq'=>25,
            'address'=>"Via della Rena, 78, 00069 Trevignano Romano RM, Italia",
            'latitude' => 42.159352916517435 ,
            'longitude'=> 12.231019504555519,
            'image'=> null,
            'house_type'=>'minicase',
            'room_type'=>'Proprietà intera',
            'price' => 70,
            'is_visible' => 1,
        ],
        [
            'title'=>'La casa Albero',
            'description'=>'Venite a trascorrere un soggiorno romantico con una coppia o famiglia, nella casa Albero.
            Una bellissima foresta di 5 ettari ospita 8 bellissime casette sospese dalla vista da sogno, unici e senza precedenti.
            Sono ospitati in alberi secolari fuori dalla vista, in osmosi con la natura.',
            'rooms'=>2,
            'beds'=> 2,
            'bathrooms'=> 1,
            'mq'=>65,
            'address'=>"Via della Macchia, 78, 00069 Trevignano Romano RM, Italia",
            'latitude' => 42.1633250367135 ,
            'longitude'=> 12.243232097724302,
            'image'=> null,
            'house_type'=>'Spazi creativi',
            'room_type'=>'Proprietà intera',
            'price' => 115,
            'is_visible' => 1,
        ],
        [
            'title'=>'Hamhall',
            'description'=>'Venite a trascorrere un soggiorno romantico con una coppia o famiglia, nella casa Albero.
            Una bellissima foresta di 5 ettari ospita 8 bellissime casette sospese dalla vista da sogno, unici e senza precedenti.
            Sono ospitati in alberi secolari fuori dalla vista, in osmosi con la natura.',
            'rooms'=>2,
            'beds'=> 2,
            'bathrooms'=> 1,
            'mq'=>60,
            'address'=>"Via Fontanella, 78, 00069 Trevignano Romano RM, Italia",
            'latitude' => 42.16426652880273 ,
            'longitude'=> 12.24452841571167,
            'image'=> null,
            'house_type'=>'Spazi creativi',
            'room_type'=>'Proprietà intera',
            'price' => 100,
            'is_visible' => 1,
        ],
        [
            'title'=>'Escape House',
            'description'=>'Escape House è un rifugio galleggiante sul lago.
            La Casa è dotata di servizi moderni, quali un soggiorno arredato con un comodo divano e un tavolino, un cucinotto con tutti gli utensili necessari, un bagno moderno e una camera con la galleria. Particolarmente interessante è una grande terrazza sul tetto con servizi per il barbecue. È una casa autosufficiente. Posto auto gratuito in loco e la casa dispone di una propria barca. Alloggio invernale pronto. Esperienza unica nella natura',
            'rooms'=>2,
            'beds'=> 2,
            'bathrooms'=> 1,
            'mq'=>65,
            'address'=>" Via della Rena, 78, 00069 Trevignano Romano RM, Italia",
            'latitude' => 42.157654066762035 ,
            'longitude'=> 12.235122716635914,
            'image'=> null,
            'house_type'=>'camper',
            'room_type'=>'Proprietà intera',
            'price' => 120,
            'is_visible' => 1,
        ],
        [
            'title'=>'Raft house',
            'description'=>'Raft house sul lago nel Parco Nazionale, vi darà un\'esperienza unica di natura, bellezza, libertà e felicità. Se vuoi fuggire dalla folla, dalla città e da tutte le cose brutte che stanno accadendo in questo momento, questo è il posto giusto per te.
            Sii nostro ospite e divertiti con tutti i tuoi sensi!',
            'rooms'=>2,
            'beds'=> 3,
            'bathrooms'=> 1,
            'mq'=>70,
            'address'=>" Via della Rena, 78, 00069 Trevignano Romano RM, Italia",
            'latitude' => 42.15615149122118 ,
            'longitude'=> 12.241041093555566,
            'image'=> null,
            'house_type'=>'camper',
            'room_type'=>'Proprietà intera',
            'price' => 135,
            'is_visible' => 1,
        ],

    ];
